export const ENVIRONMENT = {
  MAPS_API_KEY: 'INSERT KEY',
  MAP_ID: 'INSERT MAP ID',
  CAMPARI_PLACES_URL: 'INSERT CAMPARI PALACES API',
  CAMPARI_SUBSCRIPTION_URL: 'INSERT CAMPARI SUBSCRIPTION API'
};
